server:
  port: 9090
logging:
  level.root: INFO
  level:
    org.rightmove.property: INFO
    org.springframework: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG

property:
  endpoint:
    url: http://property-source/propertiesdataset